branch-defaults:
  main:
    environment: veach-remote-db-dev
  master:
    environment: veach-remote-db-dev
global:
  application_name: veach-remote-db
  branch: null
  default_ec2_keyname: veach-key
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-deploy-user
  repository: null
  sc: git
  workspace_type: Application
